/**
 * MedLens Audit Log Event Action Constants
 */

export const AUDIT_ACTIONS = {
  REPORT_UPLOADED: 'REPORT_UPLOADED',
  HUMAN_VERIFIED: 'HUMAN_VERIFIED',
  PATIENT_CREATED: 'PATIENT_CREATED',
  SUMMARY_GENERATED: 'SUMMARY_GENERATED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  DELETE_PATIENT: 'DELETE_PATIENT'
} as const;
