/**
 * MedLens Deterministic Reference Range Status Constants
 */

export const REFERENCE_RANGE_STATUSES = {
  WITHIN_PROVIDED_RANGE: 'WITHIN_PROVIDED_RANGE',
  ABOVE_PROVIDED_RANGE: 'ABOVE_PROVIDED_RANGE',
  BELOW_PROVIDED_RANGE: 'BELOW_PROVIDED_RANGE',
  REFERENCE_RANGE_UNAVAILABLE: 'REFERENCE_RANGE_UNAVAILABLE'
} as const;
